---
- name: deploying EC2
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - aws_access_key: "your access_key" 
    - aws_secret_key: "your secret_key"
  
  tasks:
  - name: Creating SSH KEY PAIRS
    amazon.aws.ec2_key:
      aws_access_key: "{{aws_access_key}}" 
      aws_secret_key: "{{aws_secret_key}}" 
      name: test_keypair
      region: us-east-1
    register: private-key


  - name: Saving the private key with the correct permission
    copy:
      content: "{{output['key']['private_key']}}"
      dest: 'private-key.pem'
      mode: 0600

  - name: Launching an EC2 Ubuntu Server
    community.aws.ec2_instance:
      key_name: test_keypair
      aws_access_key: "{{aws_access_key}}" 
      aws_secret_key: "{{aws_secret_key}}" 
      name: Ansible_Ubunto 
      instance_type: t2.micro    
      image:
        id: ami-053b0d53c279acc90
      region: us-east-1
      network:
        assign_public_ip: true
    
